[packages]
"bib latex" = ["[style=authoryear]", "biblatex"]
"colour" = "color"
"math tools" =  "mathtools"
"multi col" = "multicol"
"geometry" = "geometry"
"graphic ex" =  "graphicx"
"wrap figure" =  "wrapfig"

[document_classes]
"article" = "article"
"beamer" = "beamer"

[environments]
"abstract" = "abstract"
"add margin" = "addmargin"
"center" = "center"
"columns" = "columns"
"description" = "description"
"document" = "document"
"(enumerate | numbered list)" = "enumerate"
"equation" = "equation"
"figure" = ["figure", "[h!]"]
"flush left" = "flushleft"
"flush right" = "flushright"
"frame" = "frame"
"(list | itemise)" = "itemize"
"mini page" = "minipage"
"multi (cols | columns)" = ["multicols", "{2}"]
"quotation" = "quotation"
"quote" = "quote"
"table" = ["table", "[h!]\n\\centering"]
"long table" = "longtable"
"tabular" = ["tabular", "{llll}"]
"title page" = "titlepage"
"verbatim" = "verbatim"
"verse" = "verse"
"wrap figure" = "wrapfigure"


[command]
"author" = "author"
"[add] bib resource" = "addbibresource"
"caption" = "caption"
"chapter" = "chapter"
"column" = "column"
"frame title" = "frametitle"
"footnote" = "footnote"
"footnote text" = "footnotetext[]"
"graphics path" = "graphicspath"
"[include] graphics" = "includegraphics[width=1\\textwidth]"
"label" = "label"
"new command" = "newcommand{}[]"
"paragraph" = "paragraph"
"paren cite" = "parencite"
"part" = "part"
"reference" = "ref"
"renew command" = "renewcommand"
"sub paragraph" = "subparagraph"
"(section | heading)" = "section"
"sub (section | heading)" = "subsection"
"sub sub (section | heading)" = "subsubsection"
"text cite" = "textcite"
"[text] bold" = "textbf"
"[text] italics" = "textit"
"[text] slanted" = "textsl"
"title" = "title"
"use theme" = "usetheme"

[commandnoarg]
"centering" = "centering"
"footnote mark" = "footnotemark[]"
"horizontal line" = "hline"
"line break" = "linebreak"
"[list] item" = "item"
"make title" = "maketitle"
"new page" = "newpage"
"page break" = "pagebreak"
"print bibliography" = "printbibliography"
"table of contents" = "tableofcontents"
"text width" = "textwidth"
"vertical line" = "vline"



[symbol]
"alpha" = "alpha"
"beater" = "beta"
"gamma" = "gamma"
"delta" = "delta"
"epsilon" = "epsilon"
"zita" = "zeta"
"eater" = "eta"
"theta" = "theta"
"iota" = "iota"
"kappa" = "kappa"
"lambda" = "lambda"
"mu" = "mu"
"new" = "nu"
"zee" = "xi"
"cherry" = "pi"
"row" = "rho"
"sigma" = "sigma"
"tau" = "tau"
"upsilon" = "upsilon"
"phi" = "phi"
"chi" = "chi"
"sigh" = "psi"
"omega" = "omega"
# operators
"root" = "sqrt"
"generic root" = "root"
"integ" = "int"
"double integ" = "iint"
"triple integ" = "iiint"
"times" = "times"
"divide" = "div"
"intersection" = "cap"
"union" = "cup"
"stop" = "cdot"
"sum" = "sum"
"product" = "prod"
"(direct sum | oh plus)" = "oplus"
"(large direct sum | large oh plus)" = "bigoplus"
"plus or minus" = "pm"
"partial" = "partial"             
# fractions and related things in the lyx fractions menu
"frac" = "frac"
"(nice frack | nice fraction)" = "nicefrac"
"unit" = "unitone"
"unit two" = "unittwo"
"unit fraction " = "unitfrac"
"text fraction" = "tfrac"
"display fraction" = "dfrac"
"continued fraction" = "cfrac"
"continued fraction (left)" = "cfracleft"
"continued fraction (right)" = "cfracright"
"binomial" = "binom"
"text binomial" = "tbinom"
"display binomial" = "dbinom"
# functions
"arccoase" = "arccos"
"arcsine" = "arcsin"
"arctan" = "arctan"
"arg" = "arg"
"beemod" = "bmod"
"coase" = "cos"
"kosh" = "cosh"
"hyperbolic tangent" = "cot"
"hyperbolic cotangent" = "coth"
"cosecant" = "csc"
"degree" = "deg"
"determinant" = "det"
"dimension" = "dim"
"exp" = "exp"
"GCD" = "gcd"
"cat hom" = "hom"
"infimum" = "inf"
"kernel" = "ker"
"limit" = "lim"
"liminf" = "liminf"
"LN" = "ln"
"log" = "log"
"max" = "max"
"min" = "min"
"secant" = "sec"
"sine" = "sin"
"sinch" = "sinh"
"supremum" = "sup"
"tangent" = "tan"
"tanch" = "tanh"
"prob" = "Pr"
# relations
"subset" = "subset"
"superset" = "supset"
"strict subset" = "subsetneq"
"strict superset" = "supsetneq"
"preck" = "prec"
"preck equals" = "preceq"
"suck" = "succ"
"suck equals" = "succeq"
"approximate" = "approx"
"proportional" = "propto"
"not equal" = "neq"
"geequal" = "geq"
"leaqual" = "leq"
"member" = "in"               
# misc
"infinity" = "infty"
"dots" = "dots"               
# logic
"(land|logic and)" = "land"
"logic or" = "lor"
"primer" = "prime"
"logic not" = "lnot"
"for all" = "forall"
"there exists" = "exists" 
# math fonts
"(beebee|blackboard bold)" = "mathbb"
"roman" = "mathrm"
"bold" = "mathbf"
"bold symbol" = "boldsymbol"
"sans serif" = "mathsf"
"italic" = "mathit"
"typewriter" = "matttt"
"blackboard" = "mathbb"
"fraktur" = "mathfrak"
"calligraphic" = "mathcal"
"formal script" = "mathscr"
"normal text mode" = "textrm"
#
"left arrow" = "leftarrow"
"right arrow" = "rightarrow"
"up arrow" = "uparrow"
"down arrow" = "downarrow"
"left right arrow" = "leftrightarrow"
#
"left" = "left("
"right" = "right)"
