[r_functions]
"arrange" = "arrange"
"as character" = "as.character"
"as data frame" = "as.data.frame"
"as double" = "as.double"
"as factor" = "as.factor"
"as numeric" = "as.numeric"
"bind rows" = "bind_rows"
"cable" = "kable"
"case when" = "case_when"
"count" = "count"
"drop NA" = "drop_na"
"everything" = "everything"
"filter" = "filter"
"full join" = "full_join"
"gather" = "gather"
"glimpse" = "glimpse"
"group by" = "group_by"
"head" = "head"
"if else" = "ifelse"
"inner join" = "inner_join"
"install packages" = "install.packages"
"is NA" = "is.na"
"left join" = "left_join"
"length" = "length"
"library" = "library"
"list" = "list"
"(LM | linear model)" = "lm"
"mean" = "mean"
"mutate" = "mutate"
"names" = "names"
"paste" = "paste0"
"read CSV" = "read_csv"
"read excel" = "read_excel"
"read RDS" = "read_rds"
"rename" = "rename"
"select" = "select"
"string contains" = "str_contains"
"string detect" = "str_detect"
"string replace" = "str_replace"
"string replace all" = "str_replace_all"
"starts with" = "starts_with"
"subset" = "subset"
"sum" = "sum"
"summarise" = "summarise"
"summary" = "summary"
"tail" = "tail"
"tibble" = "tibble"
"trim white space" = "trimws"
"type [of]" = "typeof"
"ungroup" = "ungroup"
"vector" = "c"
"view" = "View"
"write RDS" = "write_rds"

[r_graph]
"aesthetics" = "aes"
"column [plot]" = "geom_col"
"density [plot]" = "geom_density"
"ex limit" = "xlim"
"facet grid" = "facet_grid"
"facet wrap" = "facet_wrap"
"histogram [plot]" = "geom_histogram"
"labels" = "labs"
"line [plot]" = "geom_line"
"path [plot]" = "geom_path"
"[GG] plot" = "ggplot"
"point [plot]" = "geom_point"
"save" = "ggsave"
"smooth [plot]" = "geom_smooth"
"theme minimal" = "theme_minimal"
"why limit" = "ylim"

[r_args]
"by" = "by = "
"colour" = "colour = "
"dodge" = "\"dodge\""
"fill" = "fill = "
"header" = "header = "
"gather" = "key = \"\",\nvalue = \"\",\n"
"labels" = "x = \"\",\ny = \"\",\ntitle = \"\",\nsubtitle = \"\",\ncaption = \"\""
"LM" = "\"lm\""
"method" = "method = "
"position" = "position = "
"year" = "year"

[r_model]
"chi square" = "qchisq"
"coefficients" = "coefficients"
"fixed effects" = "plm(,\ndata=,\nindex=c(,),\nmodel = \"within\")"
"fitted [values]" = "fitted.values"
"instrumental [variable]" = "ivreg( ~  | ,\ndata = )"
"libraries" = "library(AER)\nlibrary(car)\nlibrary(stats)\nlibrary(DescTools)\nlibrary(plm)"
"(linear | LM)" =  "lm(, data=)"
"[(linear | test)] hypothesis [test]" =  "linearHypothesis(model = ,\nc(\" = 0\"),\ntest=c(\"F\", \"Chisq\"))"
"(log it)" = "glm(,\nfamily = binomial(link=\"logit\"),\ndata=)"
"log likelihood" = "logLik()"
"normal" = "pnorm(q = , mean = , sd = )"
"pro bit" = "glm(,\nfamily = binomial(link=\"probit\"),\ndata=)"
"(pseudo | McFadden) R squared" = "PseudoR2(, which=\"McFadden\")"
"random effects" = "plm(,\ndata=,\nindex=c(,),\nmodel = \"random\")"
"residuals" = "residuals"